[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
auction = "GSEKi5UuUPiQMRWvvpvFHX8fjowv5NkRUcZc9ZMk3w33"

[registry]
url = "http://127.0.0.1:8899"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
all = "anchor keys sync && anchor build && anchor deploy && anchor test --skip-deploy --skip-build --skip-local-validator"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
