[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
auction = "6LCrNoyX2f2e1FgBfDgWAW8gSRMrzL9KpNYXAhdsig8X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/llr/.config/solana/id.json"

[scripts]
all = "anchor keys sync && anchor build && anchor deploy && anchor test --skip-deploy --skip-build --skip-local-validator"
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
