[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
auction = "8fwi3RtHHKogVd2wwqttrrMSazL9vnkttUikD4CW9y2J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/mnt/nfs/homes/loumouli/.config/solana/id.json"

[scripts]
all = "anchor keys sync && anchor build && anchor deploy && anchor test --skip-deploy --skip-build --skip-local-validator"
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
